export const ERROR = 'ERROR';
export const ERROR_CLEAR = 'ERROR_CLEAR';

export const FETCH_THEME = 'FETCH_THEME';

export const FETCH_USER = 'FETCH_ACCOUNTS';
export const FETCH_USER_SUCCESS = 'FETCH_ACCOUNTS_SUCCESS';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

